function [hand_pose] = FPAHandToCanonical(fpa_hand_pose)
    thumb_idxs = [2 7 8 9];
    index_idxs = [3 10 11 12];
    middle_idxs = [4 13 14 15];
    ring_idxs = [5 16 17 18];
    little_idxs = [6 19 20 21];
    
    hand_pose = [...
        fpa_hand_pose(1, :);...
        fpa_hand_pose(thumb_idxs, :);...
        fpa_hand_pose(index_idxs, :);...
        fpa_hand_pose(middle_idxs, :);...
        fpa_hand_pose(ring_idxs, :);...
        fpa_hand_pose(little_idxs, :)
        ];
end

