function [bone_names] = GetCanonicalFPABoneNames()
    bone_names = {'TMCP', 'TPIP', 'TDIP', 'TTIP',...
                  'IMCP', 'IPIP', 'IDIP', 'ITIP',...
                  'MMCP', 'MPIP', 'MDIP', 'MTIP',...
                  'RMCP', 'RPIP', 'RDIP', 'RTIP',...
                  'LMCP', 'LPIP', 'LDIP', 'LTIP'};
end

